#
# Generated by erpcgen 1.3.0 on Mon Sep  5 16:12:50 2016.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for dac_adc
class dac_adcClient(interface.Idac_adc):
    def __init__(self, manager):
        super(dac_adcClient, self).__init__()
        self._clientManager = manager

    def adc_get_config(self, config):
        assert type(config) is erpc.Reference, "out parameter must be a Reference object"

        # Build remote function invocation message.
        request = self._clientManager.create_request()
        outCodec = request.out_codec
        outCodec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.ADC_GET_CONFIG_ID,
                sequence=request.sequence))
        outCodec.end_write_message()

        # Send request and process reply.
        self._clientManager.perform_request(request)
        inCodec = request.in_codec
        config.value = common.AdcConfig()._read(inCodec)
        inCodec.end_read_message()

    def convert_dac_adc(self, numberToConvert, result):
        assert type(result) is erpc.Reference, "out parameter must be a Reference object"

        # Build remote function invocation message.
        request = self._clientManager.create_request()
        outCodec = request.out_codec
        outCodec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.CONVERT_DAC_ADC_ID,
                sequence=request.sequence))
        if numberToConvert is None:
            raise ValueError("numberToConvert is None")
        outCodec.write_uint32(numberToConvert)
        outCodec.end_write_message()

        # Send request and process reply.
        self._clientManager.perform_request(request)
        inCodec = request.in_codec
        result.value = inCodec.read_uint32()
        inCodec.end_read_message()

    def set_led(self, whichLed):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        outCodec = request.out_codec
        outCodec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.SET_LED_ID,
                sequence=request.sequence))
        if whichLed is None:
            raise ValueError("whichLed is None")
        outCodec.write_uint8(whichLed)
        outCodec.end_write_message()

        # Send request and process reply.
        self._clientManager.perform_request(request)
        inCodec = request.in_codec
        inCodec.end_read_message()

    def init_mag_accel(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        outCodec = request.out_codec
        outCodec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.INIT_MAG_ACCEL_ID,
                sequence=request.sequence))
        outCodec.end_write_message()

        # Send request and process reply.
        self._clientManager.perform_request(request)
        inCodec = request.in_codec
        _result = inCodec.read_int32()
        inCodec.end_read_message()
        return _result

    def read_senzor_mag_accel(self, results):
        assert type(results) is erpc.Reference, "out parameter must be a Reference object"

        # Build remote function invocation message.
        request = self._clientManager.create_request()
        outCodec = request.out_codec
        outCodec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.READ_SENZOR_MAG_ACCEL_ID,
                sequence=request.sequence))
        outCodec.end_write_message()

        # Send request and process reply.
        self._clientManager.perform_request(request)
        inCodec = request.in_codec
        results.value = common.Vector()._read(inCodec)
        inCodec.end_read_message()

    def board_get_name(self, name):
        assert type(name) is erpc.Reference, "out parameter must be a Reference object"

        # Build remote function invocation message.
        request = self._clientManager.create_request()
        outCodec = request.out_codec
        outCodec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.BOARD_GET_NAME_ID,
                sequence=request.sequence))
        outCodec.end_write_message()

        # Send request and process reply.
        self._clientManager.perform_request(request)
        inCodec = request.in_codec
        name.value = inCodec.read_string()
        inCodec.end_read_message()



