/*
 * Generated by erpcgen 1.3.0 on Mon Sep  5 16:12:47 2016.
 *
 * AUTOGENERATED - DO NOT EDIT
 */

#if !defined(_erpc_dac_adc_server_h_)
#define _erpc_dac_adc_server_h_


#ifdef __cplusplus
#include "erpc_dac_adc.h"
#include "server.h"
#include <stdint.h>
#include <stdbool.h>


/*!
 * @brief Service subclass for dac_adc.
 */
class dac_adc_service : public erpc::Service
{
public:
    dac_adc_service() : Service(kdac_adc_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * in, erpc::Codec * out);

private:
    /*! @brief Server shim for adc_get_config of dac_adc interface. */
    erpc_status_t adc_get_config_shim(erpc::Codec * in, erpc::Codec * out, uint32_t sequence);

    /*! @brief Server shim for convert_dac_adc of dac_adc interface. */
    erpc_status_t convert_dac_adc_shim(erpc::Codec * in, erpc::Codec * out, uint32_t sequence);

    /*! @brief Server shim for set_led of dac_adc interface. */
    erpc_status_t set_led_shim(erpc::Codec * in, erpc::Codec * out, uint32_t sequence);

    /*! @brief Server shim for init_mag_accel of dac_adc interface. */
    erpc_status_t init_mag_accel_shim(erpc::Codec * in, erpc::Codec * out, uint32_t sequence);

    /*! @brief Server shim for read_senzor_mag_accel of dac_adc interface. */
    erpc_status_t read_senzor_mag_accel_shim(erpc::Codec * in, erpc::Codec * out, uint32_t sequence);

    /*! @brief Server shim for board_get_name of dac_adc interface. */
    erpc_status_t board_get_name_shim(erpc::Codec * in, erpc::Codec * out, uint32_t sequence);
};

extern "C" {
#endif

typedef void * erpc_service_t;

erpc_service_t create_dac_adc_service(void);
#ifdef __cplusplus
}
#endif

#endif // _erpc_dac_adc_server_h_
